version: '3.8'

services:
    nginx1:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8870:80"
        depends_on:
            - app
        container_name: nginx_olimp

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        depends_on:
            -  db
        container_name: project_olimp

    db:
        image: mysql:8.0
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: olimp_db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8104:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: olimp_db




